from . import hr_personal_equipment_request
from . import hr_personal_equipment
from . import procurement_group
from . import stock_picking
from . import stock_move
from . import stock_rule
from . import stock_location
from . import res_company
from . import res_config_settings
