# Copyright 2021 Creu Blanca
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import api, fields, models


class HrPersonalEquipment(models.Model):
    _inherit = "hr.personal.equipment"

    location_id = fields.Many2one(related="equipment_request_id.location_id")
    procurement_group_id = fields.Many2one(
        "procurement.group",
        "Procurement Group",
        readonly=True,
        help="Moves created through this stock request will be put in this "
        "procurement group. If none is given, the moves generated by "
        "procurement rules will be grouped into one big picking.",
        related="equipment_request_id.procurement_group_id",
    )
    qty_delivered = fields.Float(
        "Delivered Quantity",
        copy=False,
        compute="_compute_qty_delivered",
        compute_sudo=True,
        store=True,
    )
    move_ids = fields.One2many(
        "stock.move", "personal_equipment_id", string="Stock Moves"
    )
    skip_procurement = fields.Boolean(compute="_compute_skip_procurement")

    @api.depends("state", "product_id", "product_id.type")
    def _compute_skip_procurement(self):
        for record in self:
            record.skip_procurement = record._skip_procurement()

    @api.depends(
        "move_ids.state",
        "move_ids.scrapped",
        "move_ids.product_uom_qty",
        "move_ids.product_uom",
    )
    def _compute_qty_delivered(self):
        for line in self:
            qty = 0.0
            for move in line.move_ids.filtered(
                lambda r, line=line: (
                    r.state == "done" and line.product_id == r.product_id
                )
            ):
                qty += move.product_uom._compute_quantity(
                    move.product_uom_qty, line.product_uom_id
                )
            line.qty_delivered = qty

    def _skip_procurement(self):
        return self.product_id.type == "service"

    def _prepare_procurement_values(self, group_id=False):
        """Prepare specific key for moves or other components that
        will be created from a procurement rule
        coming from a stock request. This method could be override
        in order to add other custom key that could be used in
        move/po creation.
        """
        return {
            "group_id": group_id or self.procurement_group_id.id or False,
            "partner_id": self.employee_id.user_id.partner_id.id,
            "personal_equipment_id": self.id,
        }

    def _get_company(self):
        return self.employee_id.company_id or self.env.company

    def _prepare_direct_picking_vals(
        self, request, source_loc, dest_loc, picking_type, company
    ):
        partner = (
            request.employee_id.user_id.partner_id
            or request.employee_id.work_contact_id
        )
        vals = {
            "picking_type_id": picking_type.id if picking_type else False,
            "location_id": source_loc.id if source_loc else False,
            "location_dest_id": dest_loc.id if dest_loc else False,
            "origin": request.name,
            "partner_id": partner.id if partner else False,
            "company_id": company.id,
        }
        if request.procurement_group_id:
            vals["group_id"] = request.procurement_group_id.id
        return vals

    def _prepare_direct_move_vals(
        self, allocation, picking, source_loc, dest_loc, company
    ):
        return {
            "name": allocation.name or allocation.product_id.display_name,
            "product_id": allocation.product_id.id,
            "product_uom_qty": allocation.quantity,
            "product_uom": (
                allocation.product_uom_id.id or allocation.product_id.uom_id.id
            ),
            "picking_id": picking.id,
            "location_id": source_loc.id if source_loc else False,
            "location_dest_id": dest_loc.id if dest_loc else False,
            "personal_equipment_id": allocation.id,
            "company_id": company.id,
        }

    def _create_direct_picking(self):
        """Creates direct stock pickings for personal equipment allocations,
        avoiding fragile pull/push rules and procurement group failures.
        """
        created_pickings = self.env["stock.picking"]
        requests = self.mapped("equipment_request_id")
        for request in requests:
            allocations = self.filtered(
                lambda a, req=request: (
                    a.equipment_request_id == req
                    and not a.skip_procurement
                    and not a.move_ids
                )
            )
            if not allocations:
                continue

            if hasattr(request, "_get_company"):
                company = request._get_company()
            else:
                company = request.employee_id.company_id or self.env.company
            warehouse = self.env["stock.warehouse"].search(
                [("company_id", "=", company.id)], limit=1
            )
            source_loc = (
                request.location_id
                or company.ppe_source_location_id
                or (warehouse.lot_stock_id if warehouse else False)
                or self.env.ref("stock.stock_location_stock", raise_if_not_found=False)
            )
            dest_loc = company.ppe_dest_location_id or self.env.ref(
                "stock.stock_location_customers", raise_if_not_found=False
            )
            picking_type = company._get_or_create_ppe_picking_type() or (
                warehouse.int_type_id if warehouse else False
            )

            vals = self._prepare_direct_picking_vals(
                request, source_loc, dest_loc, picking_type, company
            )
            picking = self.env["stock.picking"].sudo().create(vals)
            created_pickings |= picking

            moves_vals = [
                self._prepare_direct_move_vals(
                    alloc, picking, source_loc, dest_loc, company
                )
                for alloc in allocations
            ]
            self.env["stock.move"].sudo().create(moves_vals)

            picking.action_confirm()
            picking.action_assign()

            if company.ppe_auto_validate_stock and picking.state in (
                "assigned",
                "confirmed",
            ):
                for move in picking.move_ids:
                    move.quantity = move.product_uom_qty
                picking.button_validate()

        return created_pickings

    def _action_launch_procurement_rule(self):
        return self._create_direct_picking()

    def _accept_request(self):
        res = super()._accept_request()
        self._create_direct_picking()
        return res

    def _validate_allocation_vals(self):
        res = super()._validate_allocation_vals()
        if self.skip_procurement:
            res["qty_delivered"] = self.quantity
        return res
